//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.18 at 02:50:22 PM CET 
//


package it.polito.dp2.RNS.sol1.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.RNS.sol1.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParkingArea_QNAME = new QName("", "parkingArea");
    private final static QName _RoadSegment_QNAME = new QName("", "roadSegment");
    private final static QName _ShortestPath_QNAME = new QName("", "shortestPath");
    private final static QName _Vehicles_QNAME = new QName("", "vehicles");
    private final static QName _Connection_QNAME = new QName("", "connection");
    private final static QName _Place_QNAME = new QName("", "place");
    private final static QName _RnsSystem_QNAME = new QName("", "RnsSystem");
    private final static QName _Connections_QNAME = new QName("", "connections");
    private final static QName _Vehicle_QNAME = new QName("", "vehicle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.RNS.sol1.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParkingArea }
     * 
     */
    public ParkingArea createParkingArea() {
        return new ParkingArea();
    }

    /**
     * Create an instance of {@link RoadSegment }
     * 
     */
    public RoadSegment createRoadSegment() {
        return new RoadSegment();
    }

    /**
     * Create an instance of {@link ShortestPath }
     * 
     */
    public ShortestPath createShortestPath() {
        return new ShortestPath();
    }

    /**
     * Create an instance of {@link Vehicles }
     * 
     */
    public Vehicles createVehicles() {
        return new Vehicles();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link RnsSystem }
     * 
     */
    public RnsSystem createRnsSystem() {
        return new RnsSystem();
    }

    /**
     * Create an instance of {@link Connections }
     * 
     */
    public Connections createConnections() {
        return new Connections();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link Places }
     * 
     */
    public Places createPlaces() {
        return new Places();
    }

    /**
     * Create an instance of {@link CommonPlaceType }
     * 
     */
    public CommonPlaceType createCommonPlaceType() {
        return new CommonPlaceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParkingArea }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parkingArea")
    public JAXBElement<ParkingArea> createParkingArea(ParkingArea value) {
        return new JAXBElement<ParkingArea>(_ParkingArea_QNAME, ParkingArea.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadSegment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "roadSegment")
    public JAXBElement<RoadSegment> createRoadSegment(RoadSegment value) {
        return new JAXBElement<RoadSegment>(_RoadSegment_QNAME, RoadSegment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShortestPath }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shortestPath")
    public JAXBElement<ShortestPath> createShortestPath(ShortestPath value) {
        return new JAXBElement<ShortestPath>(_ShortestPath_QNAME, ShortestPath.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Vehicles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vehicles")
    public JAXBElement<Vehicles> createVehicles(Vehicles value) {
        return new JAXBElement<Vehicles>(_Vehicles_QNAME, Vehicles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Connection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "connection")
    public JAXBElement<Connection> createConnection(Connection value) {
        return new JAXBElement<Connection>(_Connection_QNAME, Connection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Place }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "place")
    public JAXBElement<Place> createPlace(Place value) {
        return new JAXBElement<Place>(_Place_QNAME, Place.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RnsSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RnsSystem")
    public JAXBElement<RnsSystem> createRnsSystem(RnsSystem value) {
        return new JAXBElement<RnsSystem>(_RnsSystem_QNAME, RnsSystem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Connections }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "connections")
    public JAXBElement<Connections> createConnections(Connections value) {
        return new JAXBElement<Connections>(_Connections_QNAME, Connections.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Vehicle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vehicle")
    public JAXBElement<Vehicle> createVehicle(Vehicle value) {
        return new JAXBElement<Vehicle>(_Vehicle_QNAME, Vehicle.class, null, value);
    }

}
